CREATE TABLE user (
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(30) NOT NULL,
	password VARCHAR(50) NOT NULL,
	email    VARCHAR(50) NOT NULL,
	
	PRIMARY KEY (id)
) ENGINE=INNODB;

CREATE TABLE friendRequest (
	id INT NOT NULL AUTO_INCREMENT,
	requestingUser INT NOT NULL,
	otherUser INT NOT NULL,
	status INT NOT NULL,

	PRIMARY KEY (id),
	FOREIGN KEY (requestingUser) REFERENCES user (id) ON DELETE CASCADE,
	FOREIGN KEY (otherUser) REFERENCES user (id) ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE debt (
	id INT NOT NULL AUTO_INCREMENT,
	amount DOUBLE NOT NULL,
	what VARCHAR(50) NOT NULL,
	comment VARCHAR(200),
	fromUser INT NOT NULL,
	toUser INT NOT NULL,
	requestingUser INT NOT NULL,
	status INT NOT NULL,

	PRIMARY KEY (id),
	FOREIGN KEY (fromUser) REFERENCES user (id) ON DELETE CASCADE,
	FOREIGN KEY (toUser) REFERENCES user (id) ON DELETE CASCADE,
	FOREIGN KEY (requestingUser) REFERENCES user (id) ON DELETE CASCADE
) ENGINE=INNODB;